const main = document.getElementById('main');
const cxt = canvas.getContext('2d');
cxt.fillStyle = 'red';
ctx.strokeStyle='red';
cxt.fillRect(0,0,40,40);
cxt.fillStyle='blue';
cxt.fillRect(1326,728,40,40);
cxt.beginPath();
cxt.moveTo(40,40);
cxt.lineTo(1326,728);
ctx.lineWidth=3;
ctx.stroke();
